In [1]:
import numpy as np
import sys


In [2]:
def index_lst(lst, component=0, rate=0):
    # component: numbers of main factors
    # rate: rate of sum(main factors)/sum(all factors)
    # rate range suggest: (0.8,1)
    # if you choose rate parameter, return index = 0 or less than len(lst)
    if component and rate:
        print('Component and rate must choose only one!')
        sys.exit(0)
    if not component and not rate:
        print('Invalid parameter for numbers of components!')
        sys.exit(0)
    elif component:
        print('Choosing by component, components are %s......' % component)
        return component
    else:
        print('Choosing by rate, rate is %s ......' % rate)
        for i in range(1, len(lst)):
            if sum(lst[:i]) / sum(lst) >= rate:
                return i
        return 0

In [4]:
# test data
mat = np.random.randint(1, 80, size=(80, 8))
# simple transform of test data
Mat = np.array(mat, dtype='float64')
print('Before PCA transforMation, data is:\n', Mat)
# print('\nMethod 1: PCA by original algorithm:')
p, n = np.shape(Mat)  # shape of Mat
cov_Mat = np.dot(Mat.T, Mat) / (p - 1)
# PCA by original algorithm using SVD
print('\nPCA by original algorithm using SVD:')
# u: Unitary matrix,  eigenvectors in columns
# d: list of the singular values, sorted in descending order
u, d, v = np.linalg.svd(cov_Mat)
Index = index_lst(d, rate=0.9)  # choose how many main factors
T2 = np.dot(Mat, u[:, :Index])  # transformed data
print('We choose %d main factors.' % Index)
print('After PCA transformation, data becomes:\n', T2)

Before PCA transforMation, data is:
 [[28. 57. 32. 62. 79. 17.  9. 32.]
 [22. 55.  9. 75. 42. 77. 23. 70.]
 [38. 68. 75. 14. 67. 14. 21.  2.]
 [21. 14. 71. 24. 18. 47. 64. 44.]
 [79. 26. 67. 14. 12. 31. 69. 74.]
 [11. 35. 72. 34.  8. 26. 18. 25.]
 [11. 63. 56. 52. 29. 14. 21. 57.]
 [34. 51. 28. 55. 16. 69. 55. 77.]
 [38.  7. 28.  5.  3. 15.  3. 65.]
 [10. 63. 71. 32. 32.  5. 25. 21.]
 [72. 62. 77. 38. 29. 62.  7. 27.]
 [47. 28. 43. 41. 34. 78. 42. 67.]
 [ 4. 22. 18. 37. 43. 38.  8.  6.]
 [74. 46.  1. 46. 39. 68. 71. 77.]
 [51.  7. 59. 18.  6. 58. 14. 70.]
 [65. 57.  5. 61. 29. 79. 58. 58.]
 [30. 28. 55. 51. 78. 37. 41. 31.]
 [ 2. 36. 61. 31.  6.  1. 66. 67.]
 [72. 57. 71. 55. 55. 35. 38. 32.]
 [22. 14. 79. 42. 50. 52. 46. 34.]
 [ 8. 76. 64. 66. 30. 26. 32. 46.]
 [56. 53. 26. 51. 13.  9. 65. 11.]
 [22. 79. 30. 78. 47. 29. 31. 43.]
 [79. 79. 65. 34.  5. 21. 35. 48.]
 [79. 16. 13. 57. 79. 46. 65. 26.]
 [49. 70. 35. 12. 55. 76. 50. 21.]
 [ 9. 68. 13. 30. 71. 32.  4. 15.]
 [37. 75. 44.  9. 